trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Kubernetes Service Connection'
#     kubernetesServiceEndpoint: 'criskubeconfigsercon'
#     command: 'login'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubeCon'
    command: 'get'
    arguments: 'pods'
    secretType: 'generic'
    secretName: 'secret'